name: Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  tests:
    name: Tests

    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-49
      options: --privileged

    strategy:
      matrix:
        variant:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: aarch64
            runner: ubuntu-24.04-arm

    runs-on: ${{ matrix.variant.runner }}

    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        build-bundle: false
        manifest-path: ${{ github.ref_type == 'tag'
          && 'studio.planetpeanut.Twinkle.yml'
          || 'studio.planetpeanut.Twinkle.devel.yml' }}
        cache-key: flatpak-builder-${{ github.sha }}
        arch: ${{ matrix.variant.arch }}
        run-tests: true
